name: Backend CD

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.1

    - name: Set up JDK 11
      uses: actions/setup-java@v4.0.0
      with:
        java-version: "11"
        distribution: "adopt"

    - name: Build App
      run: ./gradlew bootJar

    - name: Deploy Product
      uses: appleboy/scp-action@master
      with:
        username: ${{ secrets.SSH_USERNAME }}
        host: ${{ secrets.SERVER_HOST }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "./build/libs/*.jar"
        target: "/home/ubuntu/backapplication"
        strip_components: 2

    - name: Execute Server Script
      uses: appleboy/ssh-action@master
      with:
        username: ${{ secrets.SSH_USERNAME }}
        host: ${{ secrets.SERVER_HOST }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script_stop: true
        script: |
          sudo sh -x /home/ubuntu/backapplication/deploy.sh &
